# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37afd8e1daddaf28474081d39a162dae269b41e23f293806ad20e32d408c50a1b0e369972bbe1ffd9f6e46329c4d665144fab2653183c0c2ebbc95ac6197e518

test:
  secret_key_base: 9ed74bf37be93295c97b36e290158e1654e9d8cdeec00c67f40c78775b4a85c4cbb0c4e27d3dd1205e873b440947fa5bb968e7306494c491e74b4bfe034a970a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
